version: "3"

services:
  redis:
    container_name: blackjack-redis
    image: redis:7.0.8-alpine
    ports:
      - 6379:6379

  node:
    container_name: blackjack-nextjs
    entrypoint: ["yarn", "dev"]
    image: node:18.13.0-alpine
    links:
      - redis
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    working_dir: "/app"
